# Generated by Django 5.0 on 2025-03-18 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reportsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsettings',
            name='report_days',
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='report_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
