# Generated by Django 5.0 on 2025-03-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reportreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
