# Generated by Django 5.0 on 2025-04-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
